TRADUCTIONS = {
    'added lane': 'Se agrega un carril',
    'bycicle crossing': 'Cruce de bicicletas',
    'buggy warning': 'Cuidado con las carretas',
    'cattle crossing': 'Cruce de ganado',
    'intersection ahead': 'Intersección adelante',
    'curve ahead': 'Curva adelante',

    'deer crossing': 'Cruce de venados',
    'detour in 1000 ft': 'Desviación a mil pies',
    'divided highway begins': 'Inicia separación de la carretera',
    'farm machinery': 'Maquinaria agrícola',
    'fire station': 'Estación de bomberos',
    'lane end': 'Termina carril',

    'lanes shifting': 'Cambio de carriles',
    'low clearance': 'Restricción de altura',
    'low shoulder': 'Acotamiento a desnivel',
    'merging traffic': 'Incorporación de tráfico',
    'narrow bridge': 'Puente angosto',
    'pedestrian crossing': 'Cruce peatonal',

    'playground warning': '¡Cuidado! Zona de juegos',
    'prepare to stop': 'Prepárese para detenerse',
    'sharp turn': 'Curva pronunciada',
    'slippery when wet': 'Resbaloso cuando está mojado',
    'steep degree': 'Pendiente peligrosa',
    'stop ahead': 'Alto adelante',

    't intersection': 'Intersección "T"',
    'traffic light': 'Semáforo',
    'two way traffic': 'Doble sentido',
    'winding road': 'Curvas continuas',
    'watch for ice on bridges': 'Cuidado con el hielo en los puentes',
    'yield ahead': 'Ceder el paso adelante',

    'pavement ends': 'Termina el pavimento',
    'speed hump': 'Tope',
    'grooved pavement': 'Pavimento disparejo',
    'fallen rocks': 'Caída de rocas',
    'road may flood': 'Camino se puede inundar',
    'gusty winds area': 'Área de ráfagas de viento',

    'fog area': 'Área de neblina',
    'stop ahead pay toll': 'Alto adelante caseta de cobro',
    'truck roll over warning': 'Advertencia de volcadura en exceso de velocidad',
    'circular intersection': 'Glorieta',
    'lane ends': 'Termina el carril',
    'one way road': 'Un solo sentido',

    'no outlet': 'No hay salida',
    'fallen stones': 'Derrumbes',
    'detour': 'Desviación',
    'detour ahead': 'Desviación adelante',
    'fines double in work zone': 'Multas al doble en zona de trabajo',
    'flagger ahead': 'Trabajadores adelante',

    'right lane closed ahead': 'Carril derecho cerrado',
    'road work ahead': 'Trabajo en carretera adelante',
    'work crew ahead': 'Hombres trabajando adelante',
    'thru traffic merge left': 'Tráfico circulando, introducirse a la izquierda',
    'left shoulder closed half mile': 'Acotamiento cerrado a media milla',
    'right lane closed': 'Carril derecho cerrado',

    'crossing rail road': 'Cruce de ferrocarril',
    'buckle up for safety': 'Abróchese el cinturón por seguridad',
    'click it or ticket': 'Póngase el cinturón o multa',

    'school crossing': 'Cruce de escolares',
    'school bus stop ahead': 'Parada de autobús escolar adelante',
    'slow moving vehicles': 'Vehículos de baja velocidad',

    'speed advisory ahead': 'Indicador de velocidad adelante',
    'speed advisory at a roundabout': 'Indicador de velocidad en glorieta',
    'speed advisory in ramp': 'Indicador de velocidad en rampa',
    'speed limit ahead': 'Límite de velocidad adelante',

    'do not block intersection': 'No bloquear intersección',
    'do not enter': 'No entrar',
    'do not pass': 'No rebasar',
    'pass with care': 'Rebase con cuidado',
    'emergency stop only': 'Solamente paradas de emergencia',
    'keep right': 'Mantengáse a la derecha',

    'left lane must turn left': 'Carril izquierdo debe dar vuelta a la izquierda',
    'left on green arrow only': 'Vuelta a la izquierda solamente con flecha en verde',
    'left turn signal': 'Vuelta a la izquirda con señal',
    'left turn yield on green': 'Permitida vuelta a la izquierda con luz verde',
    '2 hours parking': '2 horas de estacionamiento',
    'minimum speed': 'Velocidad mínima',
    'multiple turns': 'Vueltas múltiples',
    'no left turn': 'No vuelta a la izquierda',

    'no parking': 'No estacionarse',
    'no parking anytime': 'No estacionarse a ninguna hora',
    'no right turns': 'No vuelta a la derecha',
    'no trucks': 'No camiones',
    'no turn on red': 'No dar vuelta en rojo',
    'no u turn': 'No dar vuelta en "U"',
    'one way': 'Un solo sentido',
    'restricted lane ends': 'Termina carril restringido',

    'reserved handicapped': 'Estacionamiento reservado para discapacitado',
    'right lane must turn right': 'Carril derecho tiene que dar vuelta a la derecha',
    'slower traffic keep right': 'Tráfico lento mantenerse a la derecha',
    'speed zone ahead': 'Zona de velocidad adelante',
    'stop': 'Alto',
    'stop here on red': 'Alto en rojo aquí',
    'tow away zone': 'Zona de grúa',
    'turn left or go through': 'Vuelta a la izquierda o sigue en tu carril',

    'turn right or go through': 'Vuelta a la derecha o sigue en tu carril',
    'center lane': 'Carril central',
    'wrong way': 'Sentido contrario',
    'yield': 'Ceder el paso',
    '4 way': '4 altos',
    'all way': '4 altos',
    'biohazard': 'Material químico peligroso',
    'hazmat': 'Líquido inflamable',

    'weigh station 1 mile': 'Estación de pesaje a 1 milla',
    'prepass': 'Pasar sin pensar',
    'by pass': 'Pasar sin pensar',
    'sidewalk closed ahead cross here': 'Banqueta cerrada adelante, cruzar aqui',
    'no overnight parking': 'No estacionarse toda la noche'
}